"""Generate the final report only from completed, verified artifacts."""
from common import *
import datetime
from collections import Counter

def table(headers,rows):
    def esc(x):return str(x).replace('|','\\|').replace('\n',' ')
    return '\n'.join(['| '+' | '.join(headers)+' |','|'+'|'.join(['---']*len(headers))+'|']+['| '+' | '.join(esc(v) for v in r)+' |' for r in rows])+'\n'
def f(x):return 'n/a' if x is None else f'{x:.6f}'
def run():
    out=V2/'run';verification=read(out/'verification.json');selection=read(out/'frozen_selection.json');result=read(out/'confirmation_results.json')
    chosen=selection['selected'];best=result['models'][chosen];metric=best['overall'];candidate=read(out/'candidate_confirmation.json')['validation'];ci=read(out/'confidence_intervals.json')
    env=read(V2/'environment.json');split=read(V2/'split.json');data=split['records'];folds=Counter(r['fold'] for r in data);sampling=read(out/'training_sampling.json')
    rt={s:read(out/f's{s}_complete.json') for s in [2,3]};retrieval_seconds=sum(v['seconds'] for v in rt.values());throughput=len(data)/retrieval_seconds;hours=1732544/throughput/3600
    ft=read(out/'features_walltime.json');serial_retrieval_seconds=retrieval_seconds;measured_feature_seconds=ft['seconds'];parallel=None;parallel_features=None
    if (V2/'benchmark_parallel/benchmark.json').exists():
        parallel=read(V2/'benchmark_parallel/benchmark.json');retrieval_seconds=parallel['seconds'];throughput=len(data)/retrieval_seconds;hours=1732544/throughput/3600
    if (V2/'benchmark_parallel/feature_benchmark.json').exists():
        parallel_features=read(V2/'benchmark_parallel/feature_benchmark.json');measured_feature_seconds=parallel_features['seconds']
    endtoend_hours=(retrieval_seconds+measured_feature_seconds)*1732544/len(data)/3600
    featpeaks=[read(p)['memory']['peak_rss_bytes'] for p in out.glob('s*_features_complete_*.json')];peak=max(sum(featpeaks),selection['memory']['peak_rss_bytes'],max(v['memory']['peak_rss_bytes'] for v in rt.values()))
    if parallel:peak=max(peak,parallel['peak_ram_bound'])
    if parallel_features:peak=max(peak,parallel_features['peak_ram_bound'])
    disk=sum(p.stat().st_size for p in V2.rglob('*') if p.is_file());v1=read(V1/'run_6000/final_results.json')['models']['boosted'];v1c=read(V1/'run_6000/candidate_report_final.json')['validation']['100']
    oldpilot=read(V2/'v1_paired_fit500.json');newpilot=read(V2/'pilot_old_500_frozen/assessment.json');freshpilot=read(V2/'pilot_new_500_frozen/assessment.json')
    # Operational gates, not organizer rules. Include feature-generation cost to avoid a misleading speed claim.
    ready=(candidate['recall']['all']['recall']>=.9865 and metric['macro_f0_5']>.9145 and hours<12 and endtoend_hours<24)
    status='READY FOR FIRST TEST INFERENCE' if ready else 'NOT READY FOR TEST INFERENCE'
    errors=read(out/f'{chosen}_errors.json');byid={r['entity_id']:r for r in data};examples=[]
    focus=sorted([r for r in errors if r['kind']=='false_positive'],key=lambda x:-x['score'])[:3]
    focus += [r for r in errors if r['kind']=='false_negative' and 'classifier_miss' in r['categories'] and 'missing_address' in r['categories']][:3]
    for e in focus:
        q=byid[e['s1']];c=e['candidate'];examples.append([e['kind'],e['s1'],e['target'],q['business_name'],c['business_name'],q['business_address'],c['business_address'] or '<missing>',','.join(e['categories'])])
    compare=[]
    for label,s in [('candidate recall','all'),('US candidate recall','US'),('India candidate recall','India'),('cross-script candidate recall','cross_script'),('missing-address candidate recall','missing_address'),('low-name-similarity candidate recall','low_name_similarity')]:compare.append([label,f(v1c['recall'][s]['recall']),f(candidate['recall'][s]['recall'])])
    compare += [['confirmation entities',1499,folds['validation']],['candidate mean',f(v1c['counts']['mean']),f(candidate['counts']['mean'])],['candidate p99',f(v1c['counts']['p99']),f(candidate['counts']['p99'])],
      ['retrieval throughput, S1/s','2.307 (includes V1 feature/cache work)',f(throughput)],['estimated full-test retrieval', '8.7 days (includes V1 feature/cache work)',f'{hours:.2f} hours (retrieval only)'],
      ['estimated retrieval + features','8.7 days',f'{endtoend_hours:.2f} hours'],['model','NumPy histogram boost',chosen],['threshold(s)','.621',selection['models'][chosen]['thresholds']],
      ['macro F0.5',f(v1['overall']['macro_f0_5']),f(metric['macro_f0_5'])],['macro precision',f(v1['overall']['macro_precision']),f(metric['macro_precision'])],['macro recall',f(v1['overall']['macro_recall']),f(metric['macro_recall'])],
      ['singleton accuracy',f(v1['overall']['singleton_accuracy']),f(metric['singleton_accuracy'])],['classifier false negatives',789,best['errors']['false_negative'].get('classifier_miss',0)],
      ['retrieval false negatives',70,best['errors']['false_negative'].get('retrieval_miss',0)],['false positives',175,metric['false_positive_links']],
      ['selected model fit/score/threshold seconds','261.89',f(selection['models'][chosen]['seconds'])],['peak RAM, conservative process bound','4.801 GiB',f'{peak/2**30:.3f} GiB'],['artifact disk','8.248 GiB',f'{disk/2**30:.3f} GiB including packages and prototype caches']]
    lines=['# Version 2 validation report','',f'**{status}**','',
      f'Completed and verified local validation on {len(data):,} fresh S1 entities against all 10,320,219 training S2/S3 records. Selected **{chosen}** on tuning entities; evaluated its frozen decisions on {folds["validation"]:,} confirmation entities. Exact macro F0.5: **{metric["macro_f0_5"]:.6f}**. Candidate recall: **{candidate["recall"]["all"]["recall"]:.4%}**.',
      'No challenge test retrieval/scoring, challenge matching_results.tsv, submission or upload was performed. V1 critical artifacts, code, report and all seven original dataset SHA256 hashes were verified unchanged.','',
      '## V1 versus V2','',table(['Measure','V1 verified original holdout','V2 fresh confirmation'],compare),
      '**Comparison limits:** V1 and V2 final scores use different entities and sample sizes. Raw FP/FN counts are not directly comparable; use rates and slice recall. V1’s published retrieval timer included features and cache serialization; V2 reports both retrieval-only and retrieval-plus-feature estimates to expose that difference. Runtime estimates exclude future test-index construction, model scoring, final TSV serialization and distribution/hardware variation.',
      f'V1 classifier misses were 789/5190 = {789/5190:.2%} of true links. V2 classifier misses are {best["errors"]["false_negative"].get("classifier_miss",0)}/{candidate["recall"]["all"]["true"]} = {best["errors"]["false_negative"].get("classifier_miss",0)/candidate["recall"]["all"]["true"]:.2%}. V2 cluster-bootstrap 95% interval for F0.5: {ci[chosen]}.','',
      '## Context, audit and authority','',
      'Read in full amazon_ml_challenge_context.md, dataset_context.md, codex_operating_instructions.md, dataset_analysis_report.md and baseline_validation_report.md. Read the official README, dataset_summary.json, organizer validator, experiment_log.jsonl and all V1 implementation/test/reproduction files. Inventoried all V1 caches and verified critical manifests. experiments.csv was not found in the project/parent tree; this run creates a CSV view of the existing JSONL log plus its new entry. No separate organizer clarifications or referenced Pasted text(4).txt was found. No missing rules were invented.',
      'The official README governs conflicts. The context overstates validator defaults: ID existence requires --check-ids, and candidate-subset violations only warn. V2 separately enforces candidate membership and runs ID checking. The explicit beta=.5 formula governs the imprecise precision-weight prose. The current user request authorizes ordinary dependencies and prioritizes classifier quality together with retrieval feasibility, superseding V1’s no-install scope and any interpretation that a 99.5% working target alone prohibits matcher comparison.','',
      '## Environment and licenses','',table(['Package','Installed version'],sorted(env['packages'].items())),
      'Packages were installed under artifacts/v2/packages. Exact pinned dependencies: code/business_entity_resolution/v2/requirements.txt. LightGBM’s bundled LICENSE is MIT; XGBoost metadata and bundled LICENSE declare Apache-2.0. Selected trees were learned only from official fitting labels. Saved parameter counts are conservative counts of numeric model values/nodes, far below 8B. AnyAscii is an ISC-licensed deterministic character mapping used solely as a normal local transliteration library, not a model or business lookup. Full dependency metadata/license paths are in environment.json. No pretrained model or identity data was downloaded.',
      f'Python: {env["python"].splitlines()[0]}. Physical RAM: {env["ram"]["total"]/2**30:.2f} GiB; available at audit: {env["ram"]["available"]/2**30:.2f} GiB. Windows CIM inventory was denied; psutil supplied RAM measurements.','',
      '## V1 bottleneck profile','',
      'A deterministic 30-fitting-entity, two-source cProfile run measured 113.47 seconds and 21,391 pairs. cProfile adds overhead and inclusive times overlap; these numbers identify hot paths rather than replace the original wall-clock benchmark.',
      table(['Component','Measured seconds / finding'],[['SQLite execute self time','79.267; 76,039 calls'],['FTS cumulative','69.170'],['target fetch + view cumulative','29.069; 75,619 gets'],['normalization/view cumulative','18.173'],['ranking (sorted) cumulative','35.098; includes nested fetch/scoring'],['TF-IDF cosine cumulative','6.185'],['feature generation cumulative','6.568'],['route union/dedup add cumulative','0.309'],['compression self time','0.585; JSON serialization/record cache adds further cost']]),
      'Separate unprofiled FTS route measurements, including address-token and numeric-address search, are in v1_route_timing.json. Raw call records and the complete profile are in v1_profile.json/.txt/.prof. Disk I/O timings are process-level wall times including filesystem cache; no physical-device bandwidth claim is made.','',
      table(['Unprofiled route/stage','Seconds'],[[k,f(v)] for k,v in read(V2/'v1_route_timing.json')['seconds'].items()]),
      'Removed bottlenecks: native sparse batched top-k replaces FTS search; batched corpus fetches replace per-record SQLite access; normalized target fields are reused from versioned caches; RapidFuzz replaces SequenceMatcher edit work. Remaining Python work is bounded candidate feature generation, not loops comparing every query against every target.','',
      '## Split and leakage controls','',
      f'Seed 20260926. Fit {folds["fit"]:,}, tune {folds["tune"]:,}, confirmation {folds["validation"]:,}; {split["groups"]:,} groups, maximum {split["largest_group"]} entities. Excluded all V1 entities and matching V1 sampled suffix-name/reordered-address keys. Grouped new entities by those keys and shared positive target IDs. Balanced country × 0/1/2/3/4/5+ cardinality plus cross-script, missing-address, low-name-similarity and common-name indicators. Exact split IDs and all stratum counts are persisted in split.json/split_ids.tsv.',
      'Confirmation labels were used only to balance the split before modeling, and evaluated only after the model/threshold freeze. All retrieval changes used fitting-only pilots. IDF and indexes use unlabeled full training-target text. Calibration was not fitted. Early stopping and threshold/model selection use tune only. Group checks verify no shared grouping key or positive target crosses folds. Group-order ties and tuning-half assignments use the inherited stable hash seed 2026; pool selection, sampling, tree seeds and bootstrap use 20260926. These are practical sampled clusters, not a proof against every semantic near-duplicate.','',
      '## Retrieval architecture and controlled experiments','',
      'Separate S2/S3 indexes; 250,000-target partitions; full-corpus hashed binary TF-IDF in 2^20 dimensions. Word and 3–5-gram name routes; word/numeric/postal and trigram address routes; original Unicode plus local transliteration view; leading-zero numeric normalization. Common-feature pruning: character DF >3%, word DF >10%. Native sparse top-k returns bounded results; no dense S1×target similarity array. Exact name, suffix name and reordered-address routes are batch SQL joins. Suffix equality never declares a match.',
      'Initial sampled-vocabulary retrieval omitted rare names/address fragments. Full-corpus hashing removes that vocabulary gap at the cost of possible hash collisions. Targeted routes search non-Latin target names with transliteration 2–4-grams, missing-address targets with name 3–5-grams, and joint name/address evidence. The numeric route feature means numeric overlap within address-word retrieval; it is not a separate strict numeric-only index. Country equality is a feature, not a closed country list or exclusion.',
      'Final policy: ordinary routes retrieve 100, then retain ranks through 50 for every target and through 100 for non-Latin/missing-address targets. Three rescue routes retain 50 each. Filtering precedes scoring; the saved final candidate JSONL and confirmation candidate TSV are the exact model input set. Larger raw route caches are explicitly earlier retrieval artifacts.',
      table(['Paired fitting control, same 500 V1 entities','Candidate recall','Mean candidates'],[['V1 frozen candidates',f(oldpilot['recall']['all']['recall']),f(oldpilot['counts']['mean'])],['V2 final policy',f(newpilot['recall']['all']['recall']),f(newpilot['counts']['mean'])]]),
      f'Fresh 500-fitting-entity final-policy pilot recall: {freshpilot["recall"]["all"]["recall"]:.4%}. Pilot comparisons and 10/20/50/100 budget results are retained, including failed/weaker prototypes. Candidate recall was checked before matcher training. The 99.5% target remains a working target, not an organizer rule.','',
      '## Confirmation candidate quality','',table(['Slice','True links','Retrieved','Recall'],[[s,v['true'],v['found'],f(v['recall'])] for s,v in candidate['recall'].items()]),
      table(['Candidate statistic','Value'],list(candidate['counts'].items())),f'Perfect-classifier candidate oracle macro F0.5: {candidate["oracle"]["macro_f0_5"]:.6f}. Every official true link remains in recall denominators; no positives were injected into candidates.','',
      '## Matcher, features and hard negatives','',
      '80 features: V1’s 59 concepts; 12 focused string/partial-address/transliteration/noisy-number/relative-evidence features; nine route hit/rank/score values for the three rescue routes. Feature order is saved in frozen_selection.json and feature completion manifests. Name edit changes from SequenceMatcher to RapidFuzz normalized Indel; retrieval scores/ranks change to sparse routes, so V1 model weights are not silently reused on changed feature semantics.',
      f'Fitting pair sampling: {sampling}. All three models use the same candidates, fitting rows and weights. Missing-address, common/exact names, strong-address/co-location and numeric conflicts remain probabilistic evidence. No top-1 or mandatory-link rule is used.',
      table(['Model','Tune F0.5','Threshold S2/S3','Confirmation F0.5','Macro P','Macro R','Parameters/upper bound','Fit/score/search seconds'],[[m,f(v['tune']['macro_f0_5']),v['thresholds'],f(result['models'][m]['overall']['macro_f0_5']),f(result['models'][m]['overall']['macro_precision']),f(result['models'][m]['overall']['macro_recall']),v['parameters'],f(v['seconds'])] for m,v in selection['models'].items()]),
      'Logistic uses standardized L2 regression. LightGBM uses up to 600 trees, 31 leaves, learning rate .04, leaf L2=5; XGBoost up to 600 depth-6 trees, rate .05, L2=5. Both use tuning log-loss early stopping (60 rounds). Full configurations are saved. Model reload predictions match saved tuning scores. Logistic is a sanity comparator; final choice is the better tuning LightGBM/XGBoost model.',
      'Broad threshold search followed by 51-point refinement optimizes exact macro F0.5. Every above-threshold pair is predicted. Source thresholds are adopted only with >.002 overall tuning gain and >.001 in each deterministic tuning half; decisions, calibration bins, all threshold metrics and grids are saved per model. No France-specific threshold.','',
      '## Final diagnostics','',table(['Measure','Value'],[[k,v] for k,v in metric.items() if not isinstance(v,dict)]),
      table(['Links per entity','True count','Predicted count'],[['5+' if k=='5' else k,metric['true_counts'].get(k,0),metric['prediction_counts'].get(k,0)] for k in ['0','1','2','3','4','5']]),
      table(['Entity slice','N','F0.5','Macro precision','Macro recall','Singleton accuracy'],[[s,v['n_entities'],f(v['macro_f0_5']),f(v['macro_precision']),f(v['macro_recall']),f(v['singleton_accuracy'])] for s,v in best['entity_slices'].items()]),
      'Source entity metrics restrict each S1 set to S2/S3 and apply the same singleton convention. Difficulty metrics below are link metrics, not alternative official scores. Low-name similarity is V1 folded 3–5-gram Jaccard <.2; common-name frequency >=5; cross-script uses differing Unicode letter-script sets with a non-Latin target.',
      table(['Link slice','Truth','Predicted','TP','Precision','Recall'],[[s,v.get('truth',0),v.get('predicted',0),v.get('tp',0),f(v['precision']),f(v['recall'])] for s,v in best['link_slices'].items()]),
      table(['Error','Category (overlapping)','Links'],[[kind,c,n] for kind,cs in best['errors'].items() for c,n in sorted(cs.items(),key=lambda x:-x[1])]),
      'False-merge and missed-link records with IDs, scores and text are saved in each model’s errors JSON. Categories overlap. Strong-address errors can reflect co-located businesses; cross-script/partial names and missing addresses remain difficult. These are error descriptions, not allegations of incorrect labels.','',
      'Focused findings: 105 false-positive links have strong address similarity; weak names with partial/shared addresses can also be scored overconfidently (for example QA Desire Ltd versus QA Direct Ltd). Missing addresses account for 216 missed links, of which 200 were retrieved and rejected. Cross-script link recall improved substantially, but candidate retrieval still misses 48 of 620 cross-script links. These confirmation findings are for future experiments, not changes to the frozen model.',
      table(['Error','S1','Target','Query name','Candidate name','Query address','Candidate address','Categories'],examples),
      '## Runtime, memory, disk and cache locations','',
      table(['Stage','Seconds','Peak process RAM GiB'],[[f'S{s} retrieval',f(v['seconds']),f(v['memory']['peak_rss_bytes']/2**30)] for s,v in rt.items()]+[['Four-worker feature generation',f(ft['seconds']),f(sum(featpeaks)/2**30)],['All model training/selection',f(selection['seconds']),f(selection['memory']['peak_rss_bytes']/2**30)],['Verification',f(verification['seconds']),f(verification['memory']['peak_rss_bytes']/2**30)]]),
      f'Retrieval throughput: {throughput:.2f} S1/s across both complete target corpora, measured on 10,000 entities. Linear full-test retrieval estimate: {hours:.2f} hours; retrieval plus feature generation: {endtoend_hours:.2f} hours. This is an extrapolation, not test inference. Fixed index-load overhead makes pilot-size extrapolation pessimistic; longer French addresses and larger output volumes may increase cost. Peak RAM is a conservative sum of worker peaks, not a simultaneously sampled machine peak.',
      f'Original sequential-source validation retrieval: {serial_retrieval_seconds:.2f} seconds; four-worker features: {ft["seconds"]:.2f} seconds. Parallel replay benchmark: {parallel}; feature replay: {parallel_features}. Replay candidates and every feature value must match the original frozen run before its throughput is used. Parallel retrieval uses two source processes with six native threads each; feature replay uses eight local workers. Benchmark costs and caches are additional work in this experiment.',
      'The parallel replay benefits from previously accessed filesystem caches. Its speedup includes both concurrency and cache effects; a cold-start full run may be slower.',
      f'Disk {disk/2**30:.3f} GiB under artifacts/v2, including installed packages, preserved prototypes and binary/weighted sparse caches. index_s2/index_s3 hold normalized raw/derived Parquet and prototype matrices; index2_s2/index2_s3 hold full-corpus DF/vectorizer/sparse matrices; targeted_s2/targeted_s3 hold ID maps and rescue indexes; run holds exact candidates, features, models, thresholds, metrics and verification. Index manifests contain measured build times and fingerprints. One partition at a time bounds retrieval memory.','',
      '## Reproduction and verification','',
      'Run from the project root in PowerShell; install pinned dependencies as described in code/business_entity_resolution/v2/README.md:',
      '```powershell\n& ./code/business_entity_resolution/v2/reproduce.ps1 -Stage Prepare\n& ./code/business_entity_resolution/v2/reproduce.ps1 -Stage Pilot\n& ./code/business_entity_resolution/v2/reproduce.ps1 -Stage Validation\n& ./code/business_entity_resolution/v2/reproduce.ps1 -Stage Benchmark\n& ./code/business_entity_resolution/v2/reproduce.ps1 -Stage Verify\n```',
      'Prepare uses the completed V1 artifacts as immutable inputs; its README provides their reproduction. Use a separate version directory for changed settings. Re-running validation refits the same deterministic configuration and is reproduction, not authorization to tune on confirmation.',
      table(['Check','Result'],[[k,v] for k,v in verification.items() if k not in ['memory','seconds']]),
      'The metric is exact per-S1 macro F0.5, including true-empty/predicted-empty=1 and true-empty/nonempty=0. Supplementary macro P/R use both-empty=1 and other undefined denominators=0, as in V1. Original metric/TSV/Unicode tests and V2 sparse-product/merge/group/model tests pass. Organizer validator passes with --check-ids on training-only fixtures; prediction-subset checks are independent. Synthetic French Unicode and previously unseen country labels remain valid. No French labeled quality is claimed.','',
      '## Readiness, limitations and next experiments','',
      f'**{status}**. Operational working gates used here: candidate recall at least the V1 level (.9865), F0.5 >.9145, retrieval estimate <12 hours, and retrieval-plus-feature estimate <24 hours. These are explicitly local feasibility checks, not official challenge constraints. Observed values: recall {candidate["recall"]["all"]["recall"]:.6f}, F0.5 {metric["macro_f0_5"]:.6f}, retrieval {hours:.2f} h, retrieval+features {endtoend_hours:.2f} h.',
      'Remaining limits: 99.5% candidate recall is not guaranteed; difficult slices are smaller and less stable; character hashing/pruning approximates similarity; no French supervision; index/cache build and full-scale output costs are additional. Readiness is a local engineering assessment and does not authorize test inference.',
      'Next three experiments: (1) enlarge grouped fitting data and focus matcher/calibration work on missing-address/common-name ambiguity and overconfident partial-address merges; (2) vectorize remaining feature work and reduce sparse posting traversal, benchmarking scoring/output and France-like address lengths; (3) improve residual cross-script/numeric/partial-address retrieval using fitting-only evidence. Use a fresh confirmation set for any new selections.',
      'Stopped after verified local validation and this report. No challenge test inference or submission activity.','']
    (ROOT/'version2_validation_report.md').write_text('\n'.join(lines),encoding='utf8')
    entry={'experiment_id':'v2_seed20260926_hashed_tiered','timestamp':datetime.datetime.now(datetime.timezone.utc).isoformat(),'git_commit_or_code_fingerprint':read(out/'code_fingerprints.json'),
      'data_fingerprint':read(V1/'data_fingerprints.json'),'split_id':digest(V2/'split.json'),'random_seed':20260926,'candidate_routes':'four sparse routes, three exact keys, three targeted rescues','candidate_budgets':rt[2]['config'],
      'candidate_recall_overall':candidate['recall']['all']['recall'],'candidate_recall_s2':candidate['recall']['S2']['recall'],'candidate_recall_s3':candidate['recall']['S3']['recall'],'candidate_count_statistics':candidate['counts'],
      'model_and_version':{k:env['packages'].get(k) for k in ['lightgbm','xgboost','scikit-learn']},'feature_set':selection['features'],'negative_sampling':sampling,'thresholds':{m:v['thresholds'] for m,v in selection['models'].items()},
      'macro_f0_5':metric['macro_f0_5'],'macro_precision':metric['macro_precision'],'macro_recall':metric['macro_recall'],'singleton_metrics':{k:v for k,v in metric.items() if 'singleton' in k},'slice_metrics':best['link_slices'],
      'runtime':{'retrieval_seconds':retrieval_seconds,'feature_seconds':measured_feature_seconds,'sequential_retrieval_seconds':serial_retrieval_seconds,'four_worker_feature_seconds':ft['seconds'],'training':selection['seconds'],'estimated_test_retrieval_hours':hours,'estimated_test_retrieval_features_hours':endtoend_hours},
      'peak_memory':peak,'artifact_paths':['artifacts/v2/run','version2_validation_report.md'],'notes':status+'; fresh confirmation; no test inference; V1 preserved'}
    existing=[json.loads(line) for line in (ROOT/'experiment_log.jsonl').read_text(encoding='utf8').splitlines() if line]
    for folder,note in [('pilot_new_500','Sampled vocabulary: rare-name/address vocabulary gaps; superseded.'),('pilot_new_500_hashed','Full-corpus hashed retrieval plus two targeted routes; superseded by joint evidence.'),('pilot_new_500_joint','Joint route with flat top-100 budgets: higher candidate growth; superseded by tiered budgets.'),('pilot_new_500_frozen','Final tiered fitting-only retrieval pilot; frozen before validation.')]:
        eid='v2_'+folder
        if any(e['experiment_id']==eid for e in existing):continue
        assessment=read(V2/folder/'assessment.json')
        pilot={key:None for key in entry}
        pilot.update(experiment_id=eid,timestamp=entry['timestamp'],git_commit_or_code_fingerprint=entry['git_commit_or_code_fingerprint'],data_fingerprint=entry['data_fingerprint'],split_id=entry['split_id'],random_seed=20260926,
          candidate_routes=note,candidate_budgets={'configuration_artifacts':str(Path('artifacts/v2')/folder)},candidate_recall_overall=assessment['recall']['all']['recall'],candidate_recall_s2=assessment['recall']['S2']['recall'],candidate_recall_s3=assessment['recall']['S3']['recall'],candidate_count_statistics=assessment['counts'],slice_metrics=assessment['recall'],artifact_paths=[str(Path('artifacts/v2')/folder)],notes=note+' Retrospective log entry; timestamp is log creation. No matcher fitted; unmeasured fields are null. Per-source stage timing/configuration is preserved in the artifact directory.')
        with open(ROOT/'experiment_log.jsonl','a',encoding='utf8') as log:log.write(json.dumps(pilot,ensure_ascii=False)+'\n')
        existing.append(pilot)
    if not any(e['experiment_id']==entry['experiment_id'] for e in existing):
        with open(ROOT/'experiment_log.jsonl','a',encoding='utf8') as log:log.write(json.dumps(entry,ensure_ascii=False)+'\n')
        existing.append(entry)
    fields=list(entry)
    with open(ROOT/'experiments.csv','w',encoding='utf8',newline='') as file:
        w=csv.DictWriter(file,fieldnames=fields);w.writeheader()
        for e in existing:w.writerow({k:json.dumps(e.get(k),ensure_ascii=False) if isinstance(e.get(k),(dict,list)) else e.get(k) for k in fields})
    save(out/'readiness.json',{'status':status,'retrieval_hours':hours,'retrieval_features_hours':endtoend_hours,'report_sha256':digest(ROOT/'version2_validation_report.md')})
    print(status,metric['macro_f0_5'],'retrieval_hours',hours,'total_hours',endtoend_hours,flush=True)
if __name__=='__main__':run()
